
services:
  server:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
